### ISSUE TITLE
Build File

### ISSUE THREAD

**Issue by kidspro88** [per-gron/silk-arm-ios#2]
Hi All,

I can not build armv-6 with current version , how to fix, please ?

**Comment by per-gron** [comment]
Hi kidspro88,

Thanks for your feedback. I'd love to help, but I'm a bit busy at the moment.

Can you please post what error message(s) you receive? The more complete your report is, the better.

**Comment by kidspro88** [comment]
Hi Pereckerdal,

I got source from Skype developer website and build success.
Thank you very much,

Best Regards,
Toàn.
