### ISSUE TITLE
Compilation for ARM64

### ISSUE THREAD

**Issue by JyotirmoyB** [per-gron/silk-arm-ios#3]
Hello,
    When I try to compile for ARM64 (iPhone5s), I get the following error :
`xcrun -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk -find clang` -c -g -arch arm64 -mthumb -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk -mcpu=arm64 -mtune=arm64 -march=arm64 -mcpu=cortex-a8 -mfloat-abi=softfp -mfpu=neon -Wall -enable-threads -O3   -Iinterface -Isrc -Itest  -o src/SKP_Silk_A2NLSF.o src/SKP_Silk_A2NLSF.c
clang: warning: argument unused during compilation: '-mthumb'
clang: warning: argument unused during compilation: '-march=arm64'
clang: warning: argument unused during compilation: '-mfloat-abi=softfp'
clang: warning: argument unused during compilation: '-mfpu=neon'
clang: warning: argument unused during compilation: '-e nable-threads'
error: unknown target CPU 'cortex-a8'

**Comment by per-gron** [comment]
I believe there is no 64-bit ARM assembly version of SILK, and there probably never will. SILK has ben superseded by Opus: http://blogs.skype.com/2012/09/12/skype-and-a-new-audio-codec/

**Comment by newacct** [comment]
All apps submissions after February 1, 2015 must be built for arm64: https://developer.apple.com/news/?id=10202014a

So that means this project would become useless?

**Comment by per-gron** [comment]
Yes, probably. :-/ Porting a bunch of 32 bit assembly code to be 64 bit is not a small undertaking, I think it would be much less work to just move to the codec that's not deprecated, even though it is different.

There is still a portable C version of SILK available. It is not available in this repository, but I think building it for iOS should be fairly straight forward. When I tried to use it 2 years ago, it was so slow that it was pretty much unusable on mobile phones though.
